# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
