# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171031_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_code_nba',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
