# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_game_game_code_nba'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbaGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=20)),
                ('season_stage_id', models.IntegerField()),
                ('game_code_url', models.CharField(max_length=20)),
                ('start_time_utc', models.DateTimeField()),
                ('h_score', models.IntegerField()),
                ('h_win', models.IntegerField()),
                ('h_loss', models.IntegerField()),
                ('v_score', models.IntegerField()),
                ('v_win', models.IntegerField()),
                ('v_loss', models.IntegerField()),
                ('h_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='schedule.Team')),
                ('v_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_team', to='schedule.Team')),
            ],
        ),
    ]
