# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_nbagame_is_buzzer_beater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbagame',
            name='h_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='h_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='h_win',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='v_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='v_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='v_win',
            field=models.IntegerField(null=True),
        ),
    ]
