# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_nbagame_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiHoops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_game_id', models.CharField(max_length=20)),
                ('game_star', models.IntegerField()),
                ('game_rating', models.IntegerField()),
                ('nba_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nba_game_id', to='schedule.NbaGame')),
            ],
        ),
    ]
