# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20171128_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbaReddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('ups', models.IntegerField()),
                ('permalink', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
