# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_nbareddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbareddit',
            name='created',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
