# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_nbareddit_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbareddit',
            name='nba_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_nba_game', to='schedule.NbaGame'),
        ),
    ]
