# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_nbareddit_nba_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbagame',
            name='downloaded_box_score',
            field=models.BooleanField(default=False),
        ),
    ]
