# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_nbagame_downloaded_box_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikihoops',
            name='rating_down',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikihoops',
            name='rating_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikihoops',
            name='rating_up',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wikihoops',
            name='rating_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wikihoops',
            name='game_rating',
            field=models.IntegerField(null=True),
        ),
    ]
