# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20171211_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikihoops',
            name='rating_value',
        ),
    ]
