# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_remove_wikihoops_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikihoops',
            name='rating_percentage',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
